# Generated by Django 3.1.4 on 2021-01-05 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20210105_0038'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartManager',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='update',
        ),
        migrations.AddField(
            model_name='cart',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AddField(
            model_name='cart',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
